version: "3.9"
services:
  elastic:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.13.1"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
  kibana:
    image: "docker.elastic.co/kibana/kibana:7.13.1"
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: "http://elastic:9200"

  logstash:
    image: "docker.elastic.co/logstash/logstash:7.13.1"
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/configs/:/usr/share/logstash/pipeline/
      - ./logstash/settings/:/usr/share/logstash/config/
